version: "3"
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  gnaf_uwsgi_app:
    image: gnaf_uwsgi_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - uwsgi-run:/var/run/uwsgi/:rw
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    command: ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini", "--master", "--workers", "2", "--protocol", "uwsgi", "--enable-threads", "--chmod-socket=666", "--socket", "/var/run/uwsgi/uwsgi.sock"]
    depends_on:
      - dockerhost

  nginx:
    image: nginx:alpine
    expose:
      - "80"
      - "443"
    ports:
      - "8089:80"
      - "48089:443"
    volumes:
      - uwsgi-run:/var/run/uwsgi/:rw
      - "./nginx_conf_app.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf:ro"
      - "./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro"
      - "./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro"
      - "./dhparam.pem:/etc/ssl/certs/dhparam.pem:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - gnaf_uwsgi_app

volumes:
  uwsgi-run:
